apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic-cert
  namespace: default
spec:
  secretName: petclinic-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - petclinic.oju.app
