apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:

      # 必须使用与你之前创建 Workload Identity 对应的 KSA
      serviceAccountName: petclinic-app

      containers:
        - name: petclinic-container
          image: nginx
          ports:
            - containerPort: 8080

          # 挂载的 secret 文件路径（每个是一个文件）
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "us"
            - name: DB_HOST_FILE
              value: "/secrets/host"
            - name: DB_USER_FILE
              value: "/secrets/user"
            - name: DB_PASSWORD_FILE
              value: "/secrets/password"
            - name: DB_NAME_FILE
              value: "/secrets/dbname"

          volumeMounts:
            - name: db-secrets
              mountPath: "/secrets"
              readOnly: true

      # 使用 Secret Manager CSI Driver
      volumes:
        - name: db-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "petclinic-secrets"
