apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:

      # 必须指定 SA 才能访问 Secret Manager
      serviceAccountName: petclinic-app

      containers:
        - name: petclinic-container
          image: nginx
          ports:
            - containerPort: 8080

          # 使用 CSI 挂载的文件
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "eu"
            - name: DB_HOST_FILE
              value: "/secrets/host"
            - name: DB_USER_FILE
              value: "/secrets/user"
            - name: DB_PASSWORD_FILE
              value: "/secrets/password"
            - name: DB_NAME_FILE
              value: "/secrets/dbname"

          volumeMounts:
            - name: db-secrets
              mountPath: "/secrets"
              readOnly: true

      volumes:
        - name: db-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "petclinic-secrets"
