name: Build, Push and Deploy Petclinic

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION_EU: europe-west1
  REGION_US: us-central1
  REPO_NAME: petclinic
  IMAGE_NAME: petclinic
  SERVICE_NAME_EU: petclinic-eu
  SERVICE_NAME_US: petclinic-us
  ARTIFACT_BUCKET: petclinic-ci-artifacts

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          IMAGE_URI="europe-west1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${GITHUB_SHA}"
          echo "$IMAGE_URI" > image_uri.txt
          docker build -t "$IMAGE_URI" .

      - name: Push Docker image
        run: docker push "$(cat image_uri.txt)"

      - name: Upload IMAGE_URI artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-uri
          path: image_uri.txt


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download IMAGE_URI artifact
        uses: actions/download-artifact@v4
        with:
          name: image-uri

      - name: Read IMAGE_URI
        run: |
          IMAGE_URI=$(cat image_uri.txt)
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
      - name: Upload latest image URI to GCS
        run: |
          gsutil cp image_uri.txt gs://${{ env.ARTIFACT_BUCKET }}/latest-image.txt

      # --------------------
      # Deploy to EU
      # --------------------
      - name: Deploy EU Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME_EU \
            --image "$IMAGE_URI" \
            --region $REGION_EU \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars SPRING_PROFILES_ACTIVE=eu \
            --set-env-vars DB_HOST=${{ secrets.DB_HOST_EU }} \
            --set-env-vars DB_USER=${{ secrets.DB_USER }} \
            --set-env-vars DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --set-env-vars DB_NAME=${{ secrets.DB_NAME }}

      # --------------------
      # Deploy to US
      # --------------------
      - name: Deploy US Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME_US \
            --image "$IMAGE_URI" \
            --region $REGION_US \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars SPRING_PROFILES_ACTIVE=us \
            --set-env-vars DB_HOST=${{ secrets.DB_HOST_US }} \
            --set-env-vars DB_USER=${{ secrets.DB_USER }} \
            --set-env-vars DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --set-env-vars DB_NAME=${{ secrets.DB_NAME }}
