name: Build, Push, and Deploy Petclinic to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION_EU: europe-west1
  REGION_US: us-central1
  REPO_NAME: petclinic
  IMAGE_NAME: petclinic
  BUCKET_ARTIFACTS: petclinic-cd
  SERVICE_NAME_EU: petclinic-eu
  SERVICE_NAME_US: petclinic-us

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        IMAGE_URI="europe-west1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${GITHUB_SHA}"
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
        docker build -t $IMAGE_URI .

    - name: Push Docker image
      run: |
        docker push "$IMAGE_URI"

    - name: Upload latest image tag to GCS
      run: |
        echo "$IMAGE_URI" > latest-image.txt
        gsutil cp latest-image.txt gs://${BUCKET_ARTIFACTS}/latest-image.txt


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy EU Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME_EU \
          --image "$IMAGE_URI" \
          --region $REGION_EU \
          --platform managed \
          --allow-unauthenticated

    - name: Deploy US Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME_US \
          --image "$IMAGE_URI" \
          --region $REGION_US \
          --platform managed \
          --allow-unauthenticated
